# Config file for automatic testing at travis-ci.org

language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"

install:
  - pip install geojson
  - pip install coveralls
  - pip install pytest
  - pip install pytest-cov
  - pip install -e .

script:
  - pytest . --cov=motionless --cov-report term-missing;

after_success:
  - coveralls
